### ISSUE TITLE
Cant upload from ios app, Error: Waiting for server connection

### ISSUE THREAD

**Issue by MBTollefsen** [owncloud/ios#785]
i get a Fatal Wedav error when trying to upload photos with the app for IOS. 

The app alsow "lags" when changing accounts.("hangs" and dosent show right files and folder for the account)

 If i try other "free apps" they work perfectly. Webdav works also from Mac and PC directley. I have alsow tested on Android phones. Everything works great.

I Use Owncloud 8.1.3 on Linux 14.04
### Steps to reproduce
1. Just try to upload anything with the Owncloud app for IOS
   2.
   3.
### Expected behaviour

Photo and video are suppsoed to be upload
### Actual behaviour

I get the error in the Owncloud client for IOS: Waiting for server 
Works on all "free" apps and android, PC, Mac OR linux. Dosent work on IOS.
This started around 23 of august. 
### Server configuration

**Web server:**
Apache2

**Database:**
SQLLite

**PHP version:**
### Client

**iOS version:**
10
**ownCloud app version:**
IOS 3.5.0(84af711)
**Device model:**
Iphone 5S
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
Fatal  webdav  Exception: {"Message":"HTTP\/1.1 400 expected filesize 20084843 got 0","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #27)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Video-2016-09-2...', Resource id #27)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Video-2016-09-2...', Resource id #27, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":144}  
<!--
## If you have suggestions of enhancements
--> 
### Tell us what could be improved:
```

**Comment by SergioBertolinSG** [comment]
Hello, your server version is a bit old, perhaps you should upgrade first to 8.1.10 (current stable8.1). Or even upgrade to 9.1.1 (current stable9.1).

**Comment by MBTollefsen** [comment]
Yes the versjon is old. But all of this happend atfer the iOS 3.5.0 was released. And every free apps works. Do you have ant links on how to upgrade on ubuntu 14.04. And can i upgrade from my versjon directly to 9?

Send fra iPhone


Den 27. sep. 2016 kl. 17.22 skrev Sergio Bertolín <notifications@github.com<mailto:notifications@github.com>>:


Hello, your server version is a bit old, perhaps you should upgrade first to 8.1.10 (current stable8.1). Or even upgrade to 9.1.1 (current stable9.1).

-

**Comment by SergioBertolinSG** [comment]
https://doc.owncloud.org/server/9.1/admin_manual/maintenance/upgrade.html?highlight=upgrade

**Comment by jesmrec** [comment]
@MBTollefsen did you finally upgrade your server version? and the iOS app to the latest (3.5.1)? 

If your problem persists, you can provide us a test account in your server, so we can not reproduce it here. All details you give us will be helpful.

**Comment by MBTollefsen** [comment]
Hi,

Yes sry for late replay. Yes I updated and everything works☺

Med vennlig hilsen
Martin Bang Tøllefsen
Systemkonsulent ASP
Mobil: +47 455 14 151
E-post: martin@avarde.no<mailto:martin@avarde.no>

[Avarde_logo_blå_150px]

Telefonsupport: +47 76 95 90 00
E-postsupport: support@avarde.no<mailto:support@avarde.no>
Hjemmeside: www.avarde.no<http://www.avarde.no/>



Fra: Jesús Recio Rincón [mailto:notifications@github.com]
Sendt: Wednesday, November 23, 2016 2:13 PM
Til: owncloud/ios <ios@noreply.github.com>
Kopi: Martin Bang Tøllefsen <martin@avarde.no>; Mention <mention@noreply.github.com>
Emne: Re: [owncloud/ios] Cant upload from ios app, Error: Waiting for server connection (#785)


@MBTollefsen<https://github.com/MBTollefsen> did you finally upgrade your server version? and the iOS app to the latest (3.5.1)?

If your problem persists, you can provide us a test account in your server, so we can not reproduce it here. All details you give us will be helpful.

**Comment by jesmrec** [comment]
@MBTollefsen thank you very much for the feedback.

Now we can close that.

**Comment by patillacode** [comment]
Hi there, sorry to open this again, but for anyone that stumbles upon this in the future.

I am running OwnCloud 3.5.1 on iOS 9
OwnCloud server is 9.1.2 under a NGINX reverse proxy configuration with PHP
I was getting this error when trying to upload a picture I just took, when testing my phone's app:

Logs display:

`[24/Nov/2016:13:44:44 +0000] "PUT /owncloud/remote.php/webdav/documents/Documentation/Photo-2016-11-24-13-14-00_8063.JPG HTTP/1.1" 413 207 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.5.1"`

HTTP 413 means `Request entity too large`

Couple of things to consider:

NGINX
Add a `client_max_body_size` under your location in your site's configuration file.

PHP
Check under your `php.ini` file for `upload_max_filesize` and `post_max_size`

Hopes this helps someone.

**Comment by jesmrec** [comment]
Thank you for the useful info. We will reach it in the case that somebody suffers the same problem.

**Comment by tharsan17** [comment]
I increased the upload_max_filesize and post_max_size but still my iphone app gives same problem

**Comment by patillacode** [comment]
Hi @tharsan17 

Is your service behind NGINX?
What error code are you getting?

**Comment by tharsan17** [comment]
I am using ipage host.

when i use iphone app it says waiting for server connection

Thanks

**Comment by patillacode** [comment]
That is a little vague, the question is - is it running behind NGINX?
That is independent of what hosting service you have.

If it is I found that adding `client_max_body_size` helped me.

Do you have access to the machine where your OwnClod service runs? (maybe via SSH)

**Comment by barartm** [comment]
I have same problem, latest ios version (iOS 3.6.0) and latest owncloud version 10.0.1.5,

**Comment by nasli** [comment]
@tharsan17 the version of your ownCloud

@tharsan17 , @barartm  Please take a look what @patillacode point out, there is helpful information that will help to know the cause of your issue.

Please, take the time to describe with more detail your issue, the configuration of your server, iOS version of your device and iOS OC app version and any other details that could give us some clue or been able to reproduce and distinguish if you are having different issue.

You can follow the next template :

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:**

**Storage backend (external storage):**

**Is it running behind NGINX?**

### Client
**iOS version:**

**ownCloud app version:**

**Device model:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davivel** [comment]
Permanent solution for 413 errors requires implementing #804.

**Comment by Elypson** [comment]
Hi,

I have the same issue with iOS. I only have the app, where could I get some log?

**Actual behaviour**

In the upload tab in the mobile phone, the file shows a progress bar seemingly uploading my file. When it reaches 100%, it stops and says "Waiting for server connection"

Server configuration

Web server: Apache2.2.2

Database: MySQL 14.14 (ARM)

PHP version: 5.4.45

ownCloud version: 8.1.1 (stable)

Storage backend (external storage): some external hard drive

Is it running behind NGINX? - no clue, so probably not

Client

iOS version: 10.3.3

ownCloud app version: 3.6.2

Device model: iPhone 6

Logs

The only log I see is in the administration area and there it says:

> 
Exception: {"Message":"HTTP\/1.1 400 expected filesize 59616 got 0","Code":0,"Trace":"#0 \/var\/www\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #176)\n#1 \/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Photo-2017-09-1...', Resource id #176)\n#2 \/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('InstantUpload\/P...', Resource id #176, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/remote.php(132): require_once('\/var\/www\/apps\/f...')\n#9 {main}","File":"\/var\/www\/lib\/private\/connector\/sabre\/file.php","Line":144}

It seems that for each kind of failed upload, some of those messages is generated.

**Comment by toolman1** [comment]
I'm able to upload small files without any problems (like older photos on my iPhone), however anything newer and larger, it just sits there "Waiting for server connection" with nothing in my OwnCloud.log file. Everything else seems to work fine, but uploading anything just doesn't work.

iOS app v 3.7.5, iPhone X with latest iOS
ownCloud 10.0.8 (stable)
Dreamhost VPS Server version: Ubuntu 14.04.5 LTS (GNU/Linux 3.14.52-vs2.3.6.15-1 x86_64)
