### ISSUE TITLE
Failed Upload iOS App

### ISSUE THREAD

**Issue by RomanSch** [owncloud/ios#985]
### Steps to reproduce
1. Upload a Jpg formatted Picture directly in the App. Even every other Fileformat produces this Error.
2.
3.

### Expected behaviour
Normal upload of the File to the desired server and folder.

### Actual behaviour
iOS App tells me in the Upload Tab "Waiting for a Serverconnection". After a lot of attempts the app tells me "File not available".

### Server configuration
**Web server:**
Debian 8.10
**Database:**
MariaDB 10.0.32 
**PHP version:**
7.0.26
**ownCloud version:**
10.0.4
**Storage backend (external storage):**
none
### Client
**iOS version:**
11.2.1
**ownCloud app version:**
3.6.2 (dcf4a45)
**Device model:**
iPhone 7 MN922ZD/A
#### Web server error log
```
none belonging to ownCloud
```

#### ownCloud log (data/owncloud.log)
```
Dec 25 11:23:33 XXXX ownCloud[13392]: {webdav} Exception: {"Message":"HTTP\/1.1 404 File with name Docs\/Photo-2017-12-25-11-22-54_1426.JPG could not be located","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(966): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('Docs\/Photo-2017...')\n#1 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(1665): Sabre\\DAV\\Server->getPropertiesIteratorForPath('Docs\/Photo-2017...', Array, 0)\n#2 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php(355): Sabre\\DAV\\Server->generateMultiStatus(Object(Generator), false)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#6 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php(63): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/remote.php(165): require_once('\/var\/www\/vhosts...')\n#9 {main}","File":"\/var\/www\/vhosts\/XXXvHostPathXXX\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":199,"User":"XXXuserNameXXX"}

```
 
### Tell us what could be improved:

**Comment by nasli** [comment]
@RomanSch Thanks for your feedback, we can not reproduce here with 10.0.4, 3.6.2 and iOS 11.2.1.  for more information:

When did it stop working?
Did you just update some server configuration?
Are you using some proxy?
Are you uploading directly from the app or sending from other app?

**Comment by RomanSch** [comment]
@nasli 
- I think it stopped working for me a few weeks ago. I normally use the Mobile App not so often. 
When I discovered the issue i first updated everything to the latest versions. I also installed owncloud as a fresh installation with a backup of the database and the old Data Path. 
- I did not changed any server configurations.
- I do not use a proxy.
- The issue is not depending on the way i upload. It appears on every way wether i use the oc app or sending from another.

**Comment by nasli** [comment]
Could be related with the kind of photo
Are those photos downloaded in your device? 
Do you use iCloud stream?

You can provide us a test account in your server in apps@owncloud.com and reference this issue, thanks!

**Comment by RomanSch** [comment]
@nasli 
i checked the photo format. It was jpeg. I tested it with different kind of photos. Downloaded an made by me with the phone camera.
Yes i use the icloud stream.

I provided you access to my server. I send it to the mentioned Email address.

**Comment by RomanSch** [comment]
@nasli Hi Nasli,
any further informations on the current status?
Thanks.

**Comment by RomanSch** [comment]
The App is in this state absolutely useless for me! Maybe we can do some more investigation on this? I would really appreciate. Especially as you received an access account to my owncloud Site.

**Comment by RomanSch** [comment]
Any news on this issue?????

**Comment by jesmrec** [comment]
i have just checked your test account (thanks for sharing!!), and i tried out an upload from the camera roll. 

The core response was 413 (Payload Too Large)

> The requested resource<br/>/remote.php/webdav/Photo-2018-03-01-09-56-33_0225.JPG<br/>
does not allow request data with PUT requests, or the amount of data provided in
the request exceeds the capacity limit.

comparing with a test server with the same status.php, i can not reproduce the problem, so in our test server files are correctly uploaded. You told there neither proxy nor infras in the middle that can handle the request.

Are there any special configuration in your server?

I will perform other checks and let you informed.
