### ISSUE TITLE
Can't log on, can't write username

### ISSUE THREAD

**Issue by sorenweber** [owncloud/ios#995]
This bug appeared after updating the app to 3.7.1.
![2018-01-08 09_05_13-](https://user-images.githubusercontent.com/6850199/34665205-9ab2274e-f45f-11e7-8084-17f4233481d9.png)

### Steps to reproduce
1. Open app after it has been updated
2. Windows (attached screenshot) presents itself saying that the session has experied and asks me to log on again
3. The URL is correct (can't be changed), but the username is blank and can't be changed! The password can be written. Nothing appears to be happening in the app when (after having written the password) I press "Connect" (though the logs show differently)

### Expected behaviour
The username and password fields should both be writable, and pressing "Connect" should connect me.

### Actual behaviour
I can't write a username, and judging from the logs it is also not submitted (a '-' appears in its place). And the app does not give me any new feedback when I press "Connect", and it does not give me access.

### Server configuration
**Web server:** Apache 2.4.18-2ubuntu3.5

**Database:** MySQL 5.7.20-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1

**ownCloud version:** 10.0.0-1.1

**Storage backend (external storage):**

### Client
**iOS version:** 11.2.1

**ownCloud app version:** 3.7.1

**Device model:** iPhone 5s

#### Web server error log
```
2.130.26.224 - - [08/Jan/2018:10:18:25 +0100] "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 401 4191 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:26 +0100] "GET /owncloud/status.php HTTP/1.1" 200 4310 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:26 +0100] "GET /owncloud/status.php HTTP/1.1" 200 4312 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:27 +0100] "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 401 1056 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:27 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1187 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:27 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1347 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:27 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1181 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:27 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1349 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:28 +0100] "GET /owncloud/status.php HTTP/1.1" 200 4302 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:28 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 4340 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:28 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1012 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:30 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1337 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:30 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1353 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:30 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1179 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:30 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1351 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:31 +0100] "GET /owncloud/status.php HTTP/1.1" 200 4306 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:31 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 4340 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:31 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1012 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:32 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1181 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:32 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1353 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:32 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1183 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:32 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1349 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:33 +0100] "GET /owncloud/status.php HTTP/1.1" 200 4308 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:33 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 4342 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:33 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1012 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:35 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1335 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:35 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1359 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:35 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1187 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:35 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1351 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:36 +0100] "GET /owncloud/status.php HTTP/1.1" 200 4306 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:36 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 4338 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:36 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1012 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:37 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1339 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:37 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1355 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:37 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 401 1183 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:38 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1343 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:38 +0100] "GET /owncloud/status.php HTTP/1.1" 200 4308 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:39 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 4342 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"
2.130.26.224 - - [08/Jan/2018:10:18:39 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1012 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.1"

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"nsCmfiRR3d2OacfaJ3hf","level":0,"time":"2018-01-08T09:18:25+00:00","remoteAddr":"2.130.26.224","user":"--","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v1.php\/cloud\/capabilities?format=json","message":"Current
 user is not logged in"}
{"reqId":"xQ8KXFJI1V5aHxXdxcAg","level":0,"time":"2018-01-08T09:18:27+00:00","remoteAddr":"2.130.26.224","user":"--","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v1.php\/cloud\/capabilities?format=json","message":"Current
 user is not logged in"}
{"reqId":"WmbAaRyAGruXJWhRpEZg","level":0,"time":"2018-01-08T09:18:27+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1
 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\
\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, A
rray)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/
lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\S
erver->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"
Line\":168,\"User\":false}"}
{"reqId":"0O6XLRRQn3rlM17GvBj3","level":0,"time":"2018-01-08T09:18:27+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1
 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\
\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, A
rray)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/
lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\S
erver->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}
{"reqId":"1eAVzcoL6AYGrWWd3klV","level":0,"time":"2018-01-08T09:18:28+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}
{"reqId":"VcuUmemthkJkz78lM6YY","level":0,"time":"2018-01-08T09:18:28+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}
{"reqId":"oEMW20COhQzeWOzaeW4z","level":0,"time":"2018-01-08T09:18:30+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}
{"reqId":"PHJF6ssvMdsfZiVdqF2I","level":0,"time":"2018-01-08T09:18:30+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}
{"reqId":"MBCHNkQHfvhq1wWVfy9X","level":0,"time":"2018-01-08T09:18:31+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}
{"reqId":"OAkVCkyNj8gdyBtLEewR","level":0,"time":"2018-01-08T09:18:31+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}
{"reqId":"bwBHyCxylMyvaOmehtfM","level":0,"time":"2018-01-08T09:18:32+00:00","remoteAddr":"2.130.26.224","user":"--","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"}

```

**Comment by andreaslink-de** [comment]
I have exactly the same problem and just wanted to report it, but now I can only add, I have the same issue :-). This is pretty annoying and needs to be fixed, the only workaround I currently see is to fully remove the app and reinstall it to reenter user data, which is not really an option. So currently the iOS App is unusable.
![2018-01-07_owncloud_ios-login-issue_web](https://user-images.githubusercontent.com/13200758/34674263-888dbd46-f485-11e7-97ee-8656a4de5419.png)

**Comment by nasli** [comment]
If you would like to help us testing new version, please contact us at apps@owncloud.com and link this issue, thank you!

**Comment by nasli** [comment]
Should be fixed within 3.7.2. ;)

**Comment by andreaslink-de** [comment]
Ok, did not had time to react so far :-), but good to know you fixed it, when is it going to be deployed via app store to our devices?

**Comment by andreaslink-de** [comment]
Ah, sorry, just downloaded update and it worked immediately. So thanks, consider this issue to be fixed.
